config/routes.rb
Rails.application.routes.draw do

  root :to => 'dashboards#index'

  resources :dashboards
  resources :customers
  resources :orders
  resources :staffs
  resources :salaries
  resources :measurements

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
end

app/models/measurement.rb
class Measurement < ApplicationRecord
  belongs_to :order
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :staff
  has_one :measurement
end

app/models/salary.rb
class Salary < ApplicationRecord
  belongs_to :staff
end

app/models/staff.rb
class Staff < ApplicationRecord
  has_many :orders
  has_many :salaries
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  before_action :authenticate_user!

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
    @customer_order = Order.where(:customer_id=> params[:id], :order_delete=>'0')

    @customer_order_amount = Order.where(:customer_id=> params[:id], :order_delete=>'0').sum(:order_amount)
    @customer_order_paid = Order.where(:customer_id=> params[:id], :order_delete=>'0').sum(:order_paid)
    @customer_order_total = @customer_order.count
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(params.require(:customer).permit(:customer_name, :customer_phone, :customer_email, :customer_sex, :customer_address ))

    if @customer.save
      redirect_to customers_path, :notice=> 'Customer was successfully created.'
    else
      redirect_to new_customers_path, :alert=> 'Customer was not created.'
    end
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])

    if @customer.update(params.require(:customer).permit(:customer_name, :customer_phone, :customer_email, :customer_sex, :customer_address ))
      redirect_to customers_path, :notice=> 'Customer was successfully updated.'
    else
      redirect_to edit_customers_path, :alert=> 'Customer was not updated.'
    end
  end

  def destroy
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
  	month = Date.today
  	@orders = Order.where(:order_delete=>'0')
  	@order_due = (@orders.sum(:order_amount) - @orders.sum(:order_paid))

    @orders_processing = Order.where(:order_delete=>'0', :order_status=>'Processing')
    @order_processing = @orders_processing.count

  	@orders_ready = Order.where(:order_delete=>'0', :order_status=>'Ready')
  	@order_ready = @orders_ready.count
  	
  	@orders_confirm = Order.where(:order_delete=>'0', :order_status=>'Confirm')
  	@order_confirm = @orders_confirm.count

    @orders_delivered = Order.where(:order_delete=>'0', :order_status=>'Delivered')
    @order_delivered = @orders_delivered.count

  	@staffs = Staff.where(:staff_delete=>'0').count


  	@order_month = Order.where(:order_delete=>'0', :created_at=>month.all_month).count
    @order_month_ready = Order.where(:order_delete=>'0', :order_status=>'Ready', :created_at=>month.all_month).count
  	@order_month_delivery = Order.where(:order_delete=>'0', :order_status=>'Delivered', :created_at=>month.all_month).count
  	@order_month_total = Order.where(:order_delete=>'0', :created_at=>month.all_month).sum(:order_amount)
  	@order_month_paid = Order.where(:order_delete=>'0', :created_at=>month.all_month).sum(:order_paid)
  	@order_month_due = (@order_month_total - @order_month_paid)

    @customers = Customer.all.count

  end
end

app/controllers/measurements_controller.rb
class MeasurementsController < ApplicationController

  before_action :authenticate_user!	

  def edit
  	@measurement = Measurement.find_by_order_id(params[:id])
  end

  def update
  	@measurement = Measurement.find(params[:id])

  	if @measurement.update(params.require(:measurement).permit( :neck, :shoulder, :chest, :waist, :hips, :sleeve, :bicep, :wrist, :length, :thigh, :crotch, :ankles, :inseam, :outseam, :other_measurements))
      redirect_to orders_path , :notice=> 'Measurement was successfully updated.'
    else
      redirect_to edit_order_path, :alert=> 'Measurement was not updated.'
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :authenticate_user!	

  def index
    @orders = Order.where(:order_delete=>'0')
  end

  def show
    @order  = Order.find(params[:id])
  end

  def new
    @order = Order.new
    @customer = Customer.all
    @staff = Staff.where(:staff_delete=>'0')
  end

  def create
    @order = Order.new(params.require(:order).permit(:customer_id, :staff_id, :delivery_date, :order_amount, :order_paid, :order_status, :order_details))

    if @order.save
      Measurement.create(:order_id=>Order.last.id)
      redirect_to edit_measurement_path(Order.last.id), :notice=> 'Order was successfully created.'
    else
      redirect_to new_order_path, :alert=> 'Order was not created.'
    end
  end

  def edit
  	@order = Order.find(params[:id])
  	@customer = Customer.all
    @staff = Staff.where(:staff_delete=>'0')
  end

  def update
    @order = Order.find(params[:id])

  	if @order.update(params.require(:order).permit(:customer_id, :staff_id, :delivery_date, :order_amount, :order_paid, :order_status, :order_details))
      redirect_to orders_path , :notice=> 'Order was successfully updated.'
    else
      redirect_to edit_orders_path, :alert=> 'Order was not updated.'
    end
  end

  def destroy
  	if @order = Order.where(:id=>params[:id]).update_all(:order_delete=>'1')
      redirect_to orders_path
    end
  end
end

app/controllers/salaries_controller.rb
class SalariesController < ApplicationController

  before_action :authenticate_user!
  
  def index
    @salaries = Salary.all
  end

  def show
     @salary = Salary.find(params[:id])
  end

  def new
    @salary = Salary.new
    @staff = Staff.where(:staff_delete=>'0')
  end

  def create
    @salary = Salary.new(params.require(:salary).permit(:staff_id, :salary_date, :salary_month, :salary_paid))

    if @salary.save
      redirect_to salaries_path, :notice=> 'Salary was successfully created.'
    else
      redirect_to new_salaries_path, :alert=> 'Salary was not created.'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController

  before_action :authenticate_user!
  
  def index
    @staffs = Staff.where(:staff_delete=>'0')
  end

  def show
    @staff = Staff.find(params[:id])
    @staff_salary = Salary.where(:staff_id=>params[:id])
  end

  def new
    @staff = Staff.new
  end

  def create
    @staff = Staff.new(params.require(:staff).permit(:staff_name, :staff_phone, :staff_email, :staff_sex, :staff_address, :staff_salary, :staff_delete))

    if @staff.save
      redirect_to staffs_path, :notice=> 'Staff was successfully created.'
    else
      redirect_to new_staffs_path, :alert=> 'Staff was not created.'
    end
  end

  def edit
    @staff = Staff.find(params[:id])
  end

  def update
    @staff = Staff.find(params[:id])

    if @staff.update(params.require(:staff).permit(:staff_name, :staff_phone, :staff_email, :staff_sex, :staff_address, :staff_salary, :staff_delete))
      redirect_to staffs_path, :notice=> 'Staff was successfully updated.'
    else
      redirect_to edit_staffs_path, :alert=> 'Staff was not updated.'
    end
  end

  def destroy
    if @order = Staff.where(:id=>params[:id]).update_all(:staff_delete=>'1')
      redirect_to staffs_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/measurements_helper.rb
module MeasurementsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/salaries_helper.rb
module SalariesHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/customers/index.html.erb
                
                <% content_for :title, "Customers" %>


                <!-- Page Header -->
                <div class="content bg-gray-lighter">
                    <div class="row items-push">
                        <div class="col-sm-7">
                            <h1 class="page-heading animated zoomIn">
                                Customer <small>All Customers Data.</small>
                            </h1>
                        </div>
                        <div class="col-sm-5 text-right hidden-xs">
                            <ol class="breadcrumb push-10-t">
                                <li>Dashbord</li>
                                <li><a class="link-effect" href="">Customer</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
                <!-- END Page Header -->

                <!-- Page Content -->
                <div class="content">
                    <!-- Dynamic Table Simple -->
                    <div class="block">
                        <div class="block-header">
                            <ul class="block-options">
                                <li>
                                    <button type="button" data-toggle="block-option" data-action="fullscreen_toggle"><i class="si si-size-fullscreen"></i></button>
                                </li>
                                <li>
                                    <button type="button" data-toggle="block-option" data-action="content_toggle"><i class="si si-arrow-up"></i></button>
                                </li>
                            </ul>
                            <h3 class="block-title">Customer <small>Records</small></h3>
                        </div>
                        <div class="block-content table-responsive">
                            <!-- DataTables init on table by adding .js-dataTable-simple class, functionality initialized in js/pages/base_tables_datatables.js -->
                            <table class="table table-striped js-dataTable-full-pagination">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Name</th>
                                        <th>Phone</th>
                                        <th>Email</th>
                                        <th>sex</th>
                                        <th>Address</th>
                                        <th class="text-center">Actions</th>
                                    </tr>
                                </thead> 
                                <tbody>
                                  <% @customers.each do |customers|  %>
                                    <tr><td>C-<%= customers.id %></td>
                                        <td><%= customers.customer_name %></td>
                                        <td><%= customers.customer_phone %></td>
                                        <td><%= customers.customer_email %></td>
                                        <td><%= customers.customer_sex %></td>
                                        <td><%= customers.customer_address %></td>
                                        <td class="text-center">
                                            <div class="btn-group">
                                                <%= link_to customer_path(customers.id), :class=>'btn btn-xs btn-default' do %>
                                                    <i class="fa fa-eye"></i>
                                                <% end %>
                                                <%= link_to edit_customer_path(customers.id), :class=>'btn btn-xs btn-default' do %>
                                                    <i class="fa fa-pencil"></i>
                                                <% end %>  
                                            </div>  
                                        </td>    
                                    </tr>
                                  <% end %>
                                </tbody>
                            </table>
                        </div>
                    </div> 
                </div>
                <!-- END Page Content -->

app/views/orders/index.html.erb
                <% content_for :title, "Orders" %>


                <!-- Page Header -->
                <div class="content bg-gray-lighter">
                    <div class="row items-push">
                        <div class="col-sm-7">
                            <h1 class="page-heading animated zoomIn">
                                Order <small>All Orders Data.</small>
                            </h1>
                        </div>
                        <div class="col-sm-5 text-right hidden-xs">
                            <ol class="breadcrumb push-10-t">
                                <li>Dashbord</li>
                                <li><a class="link-effect" href="">Order</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
                <!-- END Page Header -->

                <!-- Page Content -->
                <div class="content">
                    <!-- Dynamic Table Simple -->
                    <div class="block">
                        <div class="block-header">
                            <ul class="block-options">
                                <li>
                                    <button type="button" data-toggle="block-option" data-action="fullscreen_toggle"><i class="si si-size-fullscreen"></i></button>
                                </li>
                                <li>
                                    <button type="button" data-toggle="block-option" data-action="content_toggle"><i class="si si-arrow-up"></i></button>
                                </li>
                            </ul>
                            <h3 class="block-title">Order <small>Records</small></h3>
                        </div>
                        <div class="block-content table-responsive">
                            <table class="table table-striped js-dataTable-full-pagination">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Name</th>
                                        <th>Phone</th>
                                        <th>Address</th>
                                        <th>Assign To</th>
                                        <th>Amount</th>
                                        <th>Due</th>
                                        <th>Delivery Date</th>
                                        <th>Order Status</th>
                                        <th class="text-center">Actions</th>
                                    </tr>
                                </thead> 
                                <tbody>
                                  <% @orders.each do |order|  %>
                                    <tr>
                                        <td>O-<%= order.id %></td>
                                        <td data-toggle="popover" title="Details" data-content="<%= order.order_details %>" data-placement="top"><%= order.customer.customer_name %></td>
                                        <td><%= order.customer.customer_phone %></td>
                                        <td><%= order.customer.customer_address %></td>
                                        <td><%= order.staff.staff_name %></td>
                                        <td data-toggle="popover" title="Paid" data-content="<%= order.order_paid %>" data-placement="top"><%= order.order_amount %></td>
                                        <td><%= order.order_amount - order.order_paid %></td>
                                        <td><%= order.delivery_date %></td>
                                        <% if order.order_status == 'Confirm'  %>
                                            <td class="text-center"><span class="label label-default"> <%= order.order_status %></span></td>
                                        <% elsif order.order_status == 'Processing' %>
                                            <td class="text-center"><span class="label label-warning"> <%= order.order_status %></span></td>
                                        <% elsif order.order_status == 'Ready' %>
                                            <td class="text-center"><span class="label label-success"> <%= order.order_status %></span></td>
                                        <% elsif order.order_status == 'Delivered' %>
                                            <td class="text-center"><span class="label label-primary"> <%= order.order_status %></span></td>    
                                        <% end %>
                                        <td class="text-center">
                                            <div class="btn-group">
                                                <%= link_to edit_measurement_path(order.id), :class=>'btn btn-xs btn-default' do %>
                                                    <i class="fa fa-plus"></i>
                                                <% end %>
                                                <%= link_to order_path(order.id), :class=>'btn btn-xs btn-default' do %>
                                                    <i class="fa fa-print"></i>
                                                <% end %>
                                                <%= link_to edit_order_path(order.id), :class=>'btn btn-xs btn-default' do %>
                                                    <i class="fa fa-pencil"></i>
                                                <% end %>   
                                                <%= link_to order_path(order.id), :class=>'btn btn-xs btn-default', method: :delete, data: {confirm: 'Are you sure?'} do %>
                                                    <i class="fa fa-trash-o"></i>
                                                <% end %> 
                                            </div>
                                        </td>    
                                    </tr>
                                  <% end %>
                                </tbody>
                            </table>
                        </div>
                    </div> 
                </div>
                <!-- END Page Content -->

app/views/salaries/index.html.erb
                <% content_for :title, "Salaries" %>


  				<!-- Page Header -->
                <div class="content bg-gray-lighter">
                    <div class="row items-push">
                        <div class="col-sm-7">
                            <h1 class="page-heading animated zoomIn">
                                Salary <small>All Salaries Data.</small>
                            </h1>
                        </div>
                        <div class="col-sm-5 text-right hidden-xs">
                            <ol class="breadcrumb push-10-t">
                                <li>Dashbord</li>
                                <li><a class="link-effect" href="">Salary</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
                <!-- END Page Header -->

                <!-- Page Content -->
                <div class="content">
                    <!-- Dynamic Table Simple -->
                    <div class="block">
                        <div class="block-header">
                            <ul class="block-options">
                                <li>
                                    <button type="button" data-toggle="block-option" data-action="fullscreen_toggle"><i class="si si-size-fullscreen"></i></button>
                                </li>
                                <li>
                                    <button type="button" data-toggle="block-option" data-action="content_toggle"><i class="si si-arrow-up"></i></button>
                                </li>
                            </ul>
                            <h3 class="block-title">Salary <small>Records</small></h3>
                        </div>
                        <div class="block-content table-responsive">
                            <!-- DataTables init on table by adding .js-dataTable-simple class, functionality initialized in js/pages/base_tables_datatables.js -->
                            <table class="table table-striped js-dataTable-full-pagination">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Staff Name</th>
									    <th>Staff Phone</th>
									    <th>Salary Month</th>
									    <th>Staff Salary</th>
									    <th>Salary Paid</th>
									    <th>Paid Date</th>
                                        <th class="text-center">Actions</th>
                                    </tr>
                                </thead> 
                                <tbody>
                                  <% @salaries.each do |salary|  %>
                                    <tr>
                                        <td>W-<%= salary.id %></td>
                                        <td><%= salary.staff.staff_name %></td>
								        <td><%= salary.staff.staff_phone %></td>
								        <td><%= salary.salary_month %></td>
								        <td><%= salary.staff.staff_salary %></td>
								        <td><%= salary.salary_paid %></td>
								        <td><%= salary.salary_date %></td> 
                                        <td class="text-center">
                                            <div class="btn-group">
                                                <%= link_to salary_path(salary.id), :class=>'btn btn-xs btn-default' do %>
                                                    <i class="fa fa-print"></i>
                                                <% end %>
                                            </div>
                                        </td>          
                                    </tr>
                                  <% end %>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!-- END Page Content -->

app/views/staffs/index.html.erb
                <% content_for :title, "Staffs" %>


  				<!-- Page Header -->
                <div class="content bg-gray-lighter">
                    <div class="row items-push">
                        <div class="col-sm-7">
                            <h1 class="page-heading animated zoomIn">
                                Staff <small>All Staffs Data.</small>
                            </h1>
                        </div>
                        <div class="col-sm-5 text-right hidden-xs">
                            <ol class="breadcrumb push-10-t">
                                <li>Dashbord</li>
                                <li><a class="link-effect" href="">Staff</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
                <!-- END Page Header -->

                <!-- Page Content -->
                <div class="content">
                    <!-- Dynamic Table Simple -->
                    <div class="block">
                        <div class="block-header">
                            <ul class="block-options">
                                <li>
                                    <button type="button" data-toggle="block-option" data-action="fullscreen_toggle"><i class="si si-size-fullscreen"></i></button>
                                </li>
                                <li>
                                    <button type="button" data-toggle="block-option" data-action="content_toggle"><i class="si si-arrow-up"></i></button>
                                </li>
                            </ul>
                            <h3 class="block-title">Staff <small>Records</small></h3>
                        </div>
                        <div class="block-content table-responsive">
                            <!-- DataTables init on table by adding .js-dataTable-simple class, functionality initialized in js/pages/base_tables_datatables.js -->
                            <table class="table table-striped js-dataTable-full-pagination">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Name</th>
									    <th>Phone</th>
									    <th>Email</th>
									    <th>sex</th>
									    <th>Address</th>
									    <th>Salary</th>
									    <th class="text-center">Actions</th>
                                    </tr>
                                </thead> 
                                <tbody>
                                  <% @staffs.each do |staff|  %>
                                    <tr>
                                        <td>S-<%= staff.id %></td>
                                        <td><%= staff.staff_name %></td>
								        <td><%= staff.staff_phone %></td>
								        <td><%= staff.staff_email %></td>
								        <td><%= staff.staff_sex %></td>
								        <td><%= staff.staff_address %></td>
								        <td><%= staff.staff_salary %></td>
                                        <td class="text-center">
                                            <div class="btn-group">
                                                <%= link_to staff_path(staff.id), :class=>'btn btn-xs btn-default' do %>
                                                    <i class="fa fa-eye"></i>
                                                <% end %>
                                                <%= link_to edit_staff_path(staff.id), :class=>'btn btn-xs btn-default' do %>
                                                    <i class="fa fa-pencil"></i>
                                                <% end %>
                                                <%= link_to staff_path(staff.id), :class=>'btn btn-xs btn-default', method: :delete, data: {confirm: 'Are you sure?'} do %>
                                                    <i class="fa fa-trash-o"></i>
                                                <% end %>  
                                            </div>      
                                        </td>    
                                    </tr>
                                  <% end %>
                                </tbody>
                            </table>
                        </div>
                    </div>   
                </div>
                <!-- END Page Content -->